version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientcheckoutstack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6fir1z4csrd9"
s3_prefix = "patientcheckoutstack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
